### ISSUE TITLE
#QuickSearch is slow with heavy moded game

### ISSUE THREAD

**Issue by RealKolago** [malahx/QuickMods#29]
QuickSearch needs 5 to 10 seconds until search term input appears.

Maybe this can be speed up by waiting for the input and press of a search button or some type of caching?

**Comment by malahx** [comment]
If I add an option which enable search when you "stop typing" which can be done easily with something like clicking outside the text field or typing the enter key , this could be good ?

**Comment by RealKolago** [comment]
Lets try and I report back.

**Comment by malahx** [comment]
Can you try with this dll:

* https://github.com/malahx/QuickMods/raw/master/QuickSearch/GameData/QuickMods/QuickSearch/Plugins/QuickSearch.dll (overwrite the dll on QuickMods/QuickSearch/Plugins/ and enable the enter to search option)

and tell me if it's good ;)

**Comment by malahx** [comment]
I forgot... the issue is the same in the RnD?

**Comment by RealKolago** [comment]
RnD is perfectly fine. No problem there.

**Comment by RealKolago** [comment]
Ok, it have tried the new dll. Now it hangs for a few seconds after the first letter every time.
After this the search feels quicker.
