### ISSUE TITLE
Correct the Lock GUI function

### ISSUE THREAD

**Issue by malahx** [malahx/QuickMods#33]
On many QuickMods, the Lock GUI function do nothing.

- [ ] QuickBrake
- [ ] QuickContracts
- [ ] QuickCursorHider
- [ ] QuickExit
- [ ] QuickFineControl
- [ ] QuickGoTo
- [ ] QuickHide
- [ ] QuickIVA
- [x] QuickMute
- [ ] QuickRevert
- [ ] QuickSAS
- [x] QuickSearch

**Comment by Real-Gecko** [comment]
In QuickGoTo it actually locks controls, but never unlocks 'em, so you have to use debug menu `clear all locks` feature.
This KSP locking system is pretty annoying I must admit, always causes troubles :D
