### ISSUE TITLE
QuickBrake - NotSupportedException on GUI show

### ISSUE THREAD

**Issue by ayan4m1** [malahx/QuickMods#6]
Environment: Win10 x86-64, KSP 1.2.0.1586

I wrote several pages with researched links, code samples, etc last night - GitHub 500'd every time I tried to post it, looks like they had a little hiccup according to the status site. Apologies for how slapdash this might seem - The `AssemblyLoader` class in Unity libraries is trying to use Reflection on a dynamic assembly, which is resulting in a `NotSupportedException`

I am working on a fix, didn't want to PR anything until I understood all angles of the issue. So far I am changing ToolbarWrapper.getType to be safer about the way it tries to use reflection features.

Do a find for QuickBrake through this logfile to see the progression: [KSP.log.gz](https://github.com/malahx/QuickMods/files/563969/KSP.log.gz)

**Comment by malahx** [comment]
Hello, on the last beta update I've updated the ToolbarWrapper, I think this issue have been corrected.
