### ISSUE TITLE
ArgumentOutOfRangeException: Cannot be negative.

### ISSUE THREAD

**Issue by RealKolago** [malahx/QuickMods#8]
Quick Tools dont show up.
Kerbal Space Program - 1.2.1.1604 (WindowsPlayer x64)

Full Log: https://mega.nz/#!jhsTBKrb!Vkowwk86FrACfxcDHg8edeLsSgdZkGtZZ0Io5IRbhVc

ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
  at QuickExit.QuickExit.get_relativePath () [0x00000] in <filename unknown>:0 
  at QuickExit.QBlizzyToolbar..ctor () [0x00000] in <filename unknown>:0 
  at QuickExit.QExit.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
AddonLoader:StartAddons(Startup)
AddonLoader:OnLevelLoaded(Int32)
AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
 
(Filename:  Line: -1)

[AddonLoader]: Instantiating addon 'QGoTo' from assembly 'QuickGoTo'
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
  at QuickGoTo.QuickGoTo.get_relativePath () [0x00000] in <filename unknown>:0 
  at QuickGoTo.QGoTo..ctor () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
AddonLoader:StartAddons(Startup)
AddonLoader:OnLevelLoaded(Int32)
AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
 
(Filename:  Line: -1)

**Comment by malahx** [comment]
Hello, sorry I haven't the time to test, I've quickly recompile all of them with no error seen.
If you have the time to test thanks, I will test them this week end.
https://github.com/malahx/QuickMods/releases/tag/KSP-1.2.1_20161102

**Comment by RealKolago** [comment]
Same error with the recompiled version. :-(

**Comment by Real-Gecko** [comment]
Confirming with QuickExit 2.04.

**Comment by malahx** [comment]
Hello, I've found the issue, an update soon ;)
